#
# DreamLink Node.
# Offers core functions for home devices.
#

version: "3.7"

networks: 
  dreamlink:
    name: dreamlink

services:
  node:
    build: ../../images/ipfs
    image: dreamnettech/ipfs
    container_name: dreamlink
    environment:
      IPFS_PROFILE: local-discovery
      DREAMLINK_MODE: node
      DREAMLINK_BOOTSTRAP: 1
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8081:8081
    volumes:
      - ./data:/data/ipfs
