#
# DreamLink Master Node. 
# Offers core functions to be a mainstay of the network.
#

version: "3.7"

networks: 
  dreamlink:
    name: dreamlink

services:
  server:
    build: ../../images/ipfs
    image: dreamnettech/ipfs
    container_name: dreamlink-master
    restart: always
    environment:
      IPFS_PROFILE: server
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8081:8081
    volumes:
      - ./data/ipfs:/data/ipfs

  cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: dreamlink-cluster
    restart: always
    depends_on: 
      - server
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9094:9094
      - 9095:9095
      - 9096:9096
    volumes:
      - ./data/ipfs-cluster:/data/ipfs-cluster
