version: "3.7"

networks: 
  dreamlink:
    name: dreamlink

services:
  cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: dreamlink-cluster-follow-websites
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./data:/data/ipfs-cluster
    entrypoint: 
      - /sbin/tini
      - --
      - /usr/local/bin/ipfs-cluster-follow
    command: 
      - dreamnet-websites
      - run
      - --init
      - dreamnet-websites.cluster.link.dreamnet.tech
