version: "3.7"

networks: 
  dreamlink:
    name: dreamlink

services:
  cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: dreamlink-cluster
    restart: always
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9094:9094
      - 9095:9095
      - 9096:9096
    volumes:
      - ./data:/data/ipfs-cluster
